services:

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/model-chat:/model-chat
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - psql
    networks:
      - network

  psql:
    container_name: psql
    image: postgres:13
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv_files/.env
    networks:
      - network

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/model-chat:/model-chat
      - /model-chat/node_modules
    env_file:
      - ./frontend/dotenv_files/.env
    stdin_open: true
    tty: true
    networks:
      - network

networks:
  network:
    driver: bridge