services:

  model-chat:
    container_name: model-chat
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend/model-chat:/model-chat
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./backend/dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./backend/dotenv_files/.env
