services:

  model-chat:
    container_name: model-chat
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./model-chat:/model-chat
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - mysql

  mysql:
      container_name: mysql
      image: mysql:8.2
      volumes:
        - ./data/mysql/data:/var/lib/mysql
      env_file:
        - ./dotenv_files/.env
