# Generated by Django 5.1.1 on 2024-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duomessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
