# Generated by Django 5.1.1 on 2024-09-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_duomessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='duomessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
