# Generated by Django 4.2 on 2025-01-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_access',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
